### ISSUE TITLE
Labels blank 

### ISSUE THREAD

**Issue by baj24** [kinghat/tabbed-card#17]
When I updated to v0.3.0 ,the labels are blank. When I downgraded to v0.2.0, they are fine.

**Comment by kinghat** [comment]
> When I updated to v0.3.0 ,the labels are blank. When I downgraded to v0.2.0, they are fine.

can you please post your full config and a screenshot of it?

**Comment by samuelmcconnell** [comment]
I'm having the same trouble. This is with the theme [waves](https://github.com/tgcowell/waves).

v0.2.0:
![image](https://user-images.githubusercontent.com/33598200/196194685-3c361d43-d8ad-4fd6-ad91-2693deafd713.png)

v0.3.0:
![image](https://user-images.githubusercontent.com/33598200/196194899-38bcdbe0-c4d9-4458-9431-e05475ae28a6.png)

Card config:
```
type: custom:tabbed-card
options: {}
tabs:
  - label: Sun
    card:
      type: entity
      entity: sun.sun
  - label: 3D Printer
    card:
      type: entity
      entity: person.redacted
```

**Comment by kinghat** [comment]
> I'm having the same trouble. This is with the theme [waves](https://github.com/tgcowell/waves), both light and dark.
> 
> v0.2.0: ![image](https://user-images.githubusercontent.com/33598200/196194685-3c361d43-d8ad-4fd6-ad91-2693deafd713.png)
> 
> v0.3.0: ![image](https://user-images.githubusercontent.com/33598200/196194899-38bcdbe0-c4d9-4458-9431-e05475ae28a6.png)
> 
> Card config:
> 
> ```
> type: custom:tabbed-card
> options: {}
> tabs:
>   - label: Sun
>     card:
>       type: entity
>       entity: sun.sun
>   - label: 3D Printer
>     card:
>       type: entity
>       entity: person.redacted
> ```

ya, sorry, growing pains. it was a breaking upgrade as the schema changed. the schema in the readme is the correct way moving forward: https://github.com/kinghat/tabbed-card#card-schema

```yaml
tabs:
  - card:
      type:
    styles?:
    attributes?:
      label?: string
```

**Comment by samuelmcconnell** [comment]
Confirmed, moving the label key under attributes made them reappear. Thanks!

**Comment by kinghat** [comment]
> Confirmed, moving the label key under attributes made them reappear. Thanks!

sorry about the breakage and thanks for taking the time to post your config and screenshot :pray: 

@baj24 if this doesnt fix your issue i will reopen.

**Comment by baj24** [comment]
> > Confirmed, moving the label key under attributes made them reappear. Thanks!
> 
> sorry about the breakage and thanks for taking the time to post your config and screenshot 🙏
> 
> @baj24 if this doesnt fix your issue i will reopen.

I'm still seeing blank labels after changing my config.

`type: custom:tabbed-card
options: {}
tabs:
  - card: 
    attributes:
      label: Livingroom
      type: entities
      entities:
        - type: custom:fold-entity-row
          head: light.living_room_lights
          entities:
            - type: custom:fold-entity-row
              head:
                type: custom:slider-entity-row
                entity: light.living_room_lights
              entities:
                - type: custom:slider-entity-row
                  entity: light.lamp
                - type: custom:slider-entity-row
                  entity: light.corner_lamp
                - type: custom:slider-entity-row
                  entity: light.fan_lights
                - type: custom:slider-entity-row
                  entity: light.entry
                - type: custom:fold-entity-row
                  head: light.table_lamps
                  entities:
                    - type: custom:fold-entity-row
                      head:
                        type: custom:slider-entity-row
                        entity: light.table_lamps
                        entities:
                          - type: custom:slider-entity-row
                            entity: light.table_lamp1
                            show_header_toggle: false
                          - type: custom:slider-entity-row
                            entity: light.table_lamp2
                            show_header_toggle: false
                - type: custom:slider-entity-row
                  entity: light.led_strip
                - type: custom:slider-entity-row
                  entity: light.light_bar
                - type: custom:fold-entity-row
                  head: light.stairway_2
                  entities:
                    - type: custom:slider-entity-row
                      entity: light.stairway_2
                      icon: mdi:wall-sconce
        - type: custom:mushroom-fan-card
          entity: fan.1000a81f5f
          customTheme: true
        - entity: lock.door
          icon: mdi:door
        - entity: switch.tart_burners`

**Comment by renarena** [comment]
Its still wrong in the default yaml after adding a new card.
```
type: custom:tabbed-card
options: {}
tabs:
  - label: Sun
    card:
      type: entity
      entity: sun.sun
```

**Comment by kinghat** [comment]
> Its still wrong in the default yaml after adding a new card.
> 
> ```
> type: custom:tabbed-card
> options: {}
> tabs:
>   - label: Sun
>     card:
>       type: entity
>       entity: sun.sun
> ```

good catch! https://github.com/kinghat/tabbed-card/blob/beac5c080e11b8674021d3642cde57b325c678ea/src/tabbed-card.ts#L72 this is going to be fixed in the next release!
