### ISSUE TITLE
Remove focused background?

### ISSUE THREAD

**Issue by RefineryX** [kinghat/tabbed-card#23]
Loving this addition.. thanks for you work on this!!

When changing tabs, I see that the 'active' or 'focused' background stays. However, when clicking outside of the area, the focused background is removed.

How do I remove this background entirely? 

**Demo:**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/46373533/196275050-762a8426-100f-49d9-b17f-b4047be2d1ab.gif)

**Comment by kinghat** [comment]
> Loving this addition.. thanks for you work on this!!
> 
> When changing tabs, I see that the 'active' or 'focused' background stays. However, when clicking outside of the area, the focused background is removed.
> 
> How do I remove this background entirely?

so you want it so only the active tabs indicator icon(underline) is shown?

**Comment by RefineryX** [comment]
> > Loving this addition.. thanks for you work on this!!
> > When changing tabs, I see that the 'active' or 'focused' background stays. However, when clicking outside of the area, the focused background is removed.
> > How do I remove this background entirely?
> 
> so you want it so only the active tabs indicator icon(underline) is shown?

Correct. Just the underline and not the block background.

**Comment by kinghat** [comment]
> Correct. Just the underline and not the block background.

setting your global style ripple color to transparent should work:

```
- type: custom:tabbed-card
  styles:
    --mdc-ripple-color: transparent
```

if that dosnt work for you, lmk!

**Comment by RefineryX** [comment]
Thanks so much... that worked! This is a real game changer and **thanks** again for your work on this! 

I have a couple of questions / comments:

- **GUI:** I would love if there was a GUI version.... yaml is somewhat a pain to manage esp for dashboards when there is a stack within a stack within a grid etc.

- **Tab position:** Is it possible to align the tab to the bottom and have the tabbed-content appear first?

- **Width:** I see that `--mdc-tab-height` controls the height and wondered if there is an equivalent for `width`? The current behaviour is that the tabs spread 100% of the content - evenly distributed. For example:


**Current Styling:**
![1](https://user-images.githubusercontent.com/46373533/196699865-bf991ee7-dc10-4fad-a561-431522e54c96.png)


**Shortened- stacked tabs left:**
![2](https://user-images.githubusercontent.com/46373533/196699888-e817b229-a8ec-4125-b72e-cdc84e4327e1.png)

**Shortened - stacked centered**
![3](https://user-images.githubusercontent.com/46373533/196700614-741d573c-c3f8-4c5f-ba50-3c8dc6551391.png)
_Though I believe a similar style can be done via `minWidth` but this still spreads the tabs 100%_

**Comment by kinghat** [comment]
> I have a couple of questions / comments:

for future can you keep an issue to one topic as things can easily get lost. thinking about making issues only for actual issues and feature requests go into discussions.

>     * **GUI:** I would love if there was a GUI version.... yaml is somewhat a pain to manage esp for dashboards when there is a stack within a stack within a grid etc.

already noted and in progress: https://github.com/kinghat/tabbed-card/issues/15

>     * **Tab position:** Is it possible to align the tab to the bottom and have the tabbed-content appear first?

was thinking about this and will probably end up being added at some point.

>     * **Width:** I see that `--mdc-tab-height` controls the height and wondered if there is an equivalent for `width`? The current behaviour is that the tabs spread 100% of the content - evenly distributed. For example:
> 
> 
> **Current Styling:** ![1](https://user-images.githubusercontent.com/46373533/196699865-bf991ee7-dc10-4fad-a561-431522e54c96.png)
> 
> **Shortened- stacked tabs left:** ![2](https://user-images.githubusercontent.com/46373533/196699888-e817b229-a8ec-4125-b72e-cdc84e4327e1.png)
> 
> **Shortened - stacked centered** ![3](https://user-images.githubusercontent.com/46373533/196700614-741d573c-c3f8-4c5f-ba50-3c8dc6551391.png) _Though I believe a similar style can be done via `minWidth` but this still spreads the tabs 100%_

someone else asked about this(another reason to move to single topic issues/discussions) and im not sure i really want to stray away from what the underlying components were designed to do.

**Comment by kinghat** [comment]
if you would like to open a discussion -> ideas for the bottom tab bar and your width feature it would be appreciated. i moved the other feature requests there as well.
