### ISSUE TITLE
colors styles dont follow the current theme

### ISSUE THREAD

**Issue by Jawyman42** [kinghat/tabbed-card#48]
Loving this.  I'd really like the option to put the tabs at the bottom of the cards.
Also is there a way to have the colors styles follow the current theme?

Thank you, great stuff

**Comment by kinghat** [comment]
> Loving this. I'd really like the option to put the tabs at the bottom of the cards. 

this was asked before and ive lost it somewhere. its kind of against the material design guidelines but i can see it being handy for mobile. could you please open a feature request for it here: https://github.com/kinghat/tabbed-card/discussions/categories/feature-requests

> Also is there a way to have the colors styles follow the current theme?

what colors arent following? it should be following the color variables that home assistant is using. can you provide a screenshot of your issue?

**Comment by Jawyman42** [comment]
When u assured me it should be working I dug into my code a bit. Turns out it was user error as I'm not as familiar with YAML as I'd like. Thanks again so much.
