### ISSUE TITLE
Conditional tab or conditional tab-headline

### ISSUE THREAD

**Issue by tinkerberlin** [kinghat/tabbed-card#60]
Hi there, 
is it possible to use the "conditional card" together with the "tabbed card"? 

Basically: Could one have a given tab only appear if a given condition is met? Alternatively, I assume one could use conditional cards within a tab. In that case, could one have the tab's headline be formated based on a certain condition? For example: have its background be green if a certain condition is met and red if it's not met.

**Comment by kinghat** [comment]
you can use the conditional card to some degree as shown here:

https://user-images.githubusercontent.com/16073360/210274795-96eb10e6-eff8-4f9a-a1b8-8ca091241ead.mp4

there was already a feature request along these lines for the tabs/tab labels be conditional: https://github.com/kinghat/tabbed-card/discussions/49. you can make suggestions and follow along there.

**Comment by tinkerberlin** [comment]
Thanks @kinghat ! I'll have a look at the video tomorrow. Also added this feature request / suggestion to #49 . I had seen it before posting my "report" but thought mine was sufficiently different to write this new feature request. 

Thanks anyways :-)
