### ISSUE TITLE
Add visual editor support

### ISSUE THREAD

**Issue by Grayda** [kinghat/tabbed-card#62]
I absolutely love this custom card because it keeps my dashboard nice and tidy, but editing the YAML gets tiresome after a while. Any chance of eventually adding in visual editor support, a bit like what the Home Assistant vertical / horizontal stack cards offer?

**Comment by kinghat** [comment]
this will be in the next feature release. its what ive been working on. you can follow along here: https://github.com/kinghat/tabbed-card/discussions/27
