### ISSUE TITLE
[FR] Vertical Tab Card

### ISSUE THREAD

**Issue by schmierlappe** [kinghat/tabbed-card#63]
would it be possible to have your card in a vertical layout with styling options to have for example a navigation bar on the side. 

Something like this:

![image](https://user-images.githubusercontent.com/4019953/210248923-bc7cf7e5-df6e-4faf-bc45-5f0eaff61ac7.png)

**Comment by kinghat** [comment]
> would it be possible to have your card in a vertical layout with styling options to have for example a navigation bar on the side.
> 
> Something like this:
> 
> ![image](https://user-images.githubusercontent.com/4019953/210248923-bc7cf7e5-df6e-4faf-bc45-5f0eaff61ac7.png)

this is probably as far as i will go in regards to repositioning the tabs: https://github.com/kinghat/tabbed-card/discussions/51
