### ISSUE TITLE
[Request] Add Editor UI

### ISSUE THREAD

**Issue by Cerothen** [kinghat/tabbed-card#66]
I have been trying to investigate what it would take to add a visual editor to "tabbed-card" but I haven't really used typescript so its an uphill battle. I was reviewing the editor for "lovelace-layout-card". https://github.com/thomasloven/lovelace-layout-card/blob/466df9cb051033881106dfb9029672ac7ea2a2c3/src/layout-card-editor.ts

The minimum that is really needed is the Label, icon, stacked and a cards editor (for the nested cards).

While the "tabbed-card" config itself is not complicated and can be done in YAML easily enough it prevents any and all nested card from using the visual editor. In my case I am nesting a lovelace-layout-card in each tab to give the experience of extra dashboard views nested under each tab.

The editor would certainly make the card more user friendly since it would make using other cards editors easier.

Edit: adding relevant Home Assistant info page.

https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/

**Comment by kinghat** [comment]
you can follow along with the feature request here: https://github.com/kinghat/tabbed-card/discussions/27 i should be releasing an experimental build to HACS shortly.
