### ISSUE TITLE
Fails to render the tabbed card when 1 child card is empty

### ISSUE THREAD

**Issue by mijofa** [kinghat/tabbed-card#67]
I have a couple of [Upcoming Media Cards](https://github.com/custom-cards/upcoming-media-card) tabbed together, and have found that when any one of them is empty (as will happen when I've caught up on shows)
Can't really put a useful screenshot here as there's no error or anything, just an empty card, it doesn't even show the tab bar for the other cards.

I can't really think of any other way to reproduce this issue, so maybe it is specific to Upcoming Media Card, in which case, sorry, probably not significant enough to matter.

**Comment by kinghat** [comment]
please provide your config and screenshots of it working fine and the issue you are experiencing.

**Comment by kinghat** [comment]
> please provide your config and screenshots of it working fine and the issue you are experiencing.

can be reopened if this issue is still occurring and screenshots/video/config are posted.
